name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/
            rm -rf landing_page_cicd
            git clone https://github.com/shivam0910/landing_page_cicd.git
            cd landing_page_cicd

            FRONTEND_CONTAINER_ID=$(docker ps -aqf "name=frontend")
            if [ ! -z "$FRONTEND_CONTAINER_ID" ]; then
              docker container stop $FRONTEND_CONTAINER_ID
              docker container rm $FRONTEND_CONTAINER_ID
            fi
            docker-compose -f docker-compose.prod.yml up -d --build
